# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(750, 850)
        MainWindow.setMinimumSize(QtCore.QSize(400, 500))
        MainWindow.setMaximumSize(QtCore.QSize(20000, 20000))
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -718, 717, 1768))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.frameSelectFolder = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frameSelectFolder.setObjectName(_fromUtf8("frameSelectFolder"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.frameSelectFolder)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.labelDirectory = QtGui.QLabel(self.frameSelectFolder)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.labelDirectory.setFont(font)
        self.labelDirectory.setObjectName(_fromUtf8("labelDirectory"))
        self.horizontalLayout_14.addWidget(self.labelDirectory)
        self.edit_directory_path = QtGui.QLineEdit(self.frameSelectFolder)
        self.edit_directory_path.setObjectName(_fromUtf8("edit_directory_path"))
        self.horizontalLayout_14.addWidget(self.edit_directory_path)
        self.browseDirectory = QtGui.QPushButton(self.frameSelectFolder)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseDirectory.sizePolicy().hasHeightForWidth())
        self.browseDirectory.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.browseDirectory.setFont(font)
        self.browseDirectory.setObjectName(_fromUtf8("browseDirectory"))
        self.horizontalLayout_14.addWidget(self.browseDirectory)
        self.verticalLayout_7.addWidget(self.frameSelectFolder)
        self.line_11 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.verticalLayout_7.addWidget(self.line_11)
        self.line_7 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.verticalLayout_7.addWidget(self.line_7)
        self.line_10 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.verticalLayout_7.addWidget(self.line_10)
        self.frame = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.widgetSettings = QtGui.QWidget(self.frame)
        self.widgetSettings.setObjectName(_fromUtf8("widgetSettings"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.widgetSettings)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.labelSettings = QtGui.QLabel(self.widgetSettings)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.labelSettings.setFont(font)
        self.labelSettings.setObjectName(_fromUtf8("labelSettings"))
        self.horizontalLayout_9.addWidget(self.labelSettings)
        self.comboBoxSelectSettings = QtGui.QComboBox(self.widgetSettings)
        self.comboBoxSelectSettings.setObjectName(_fromUtf8("comboBoxSelectSettings"))
        self.comboBoxSelectSettings.addItem(_fromUtf8(""))
        self.comboBoxSelectSettings.addItem(_fromUtf8(""))
        self.comboBoxSelectSettings.addItem(_fromUtf8(""))
        self.horizontalLayout_9.addWidget(self.comboBoxSelectSettings)
        self.verticalLayout_5.addWidget(self.widgetSettings)
        self.line_6 = QtGui.QFrame(self.frame)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.verticalLayout_5.addWidget(self.line_6)
        self.line_8 = QtGui.QFrame(self.frame)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.verticalLayout_5.addWidget(self.line_8)
        self.groupPreprocessing = QtGui.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupPreprocessing.setFont(font)
        self.groupPreprocessing.setObjectName(_fromUtf8("groupPreprocessing"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupPreprocessing)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.widgetWordList = QtGui.QWidget(self.groupPreprocessing)
        self.widgetWordList.setObjectName(_fromUtf8("widgetWordList"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widgetWordList)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.labelWordsList = QtGui.QLabel(self.widgetWordList)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.labelWordsList.setFont(font)
        self.labelWordsList.setObjectName(_fromUtf8("labelWordsList"))
        self.horizontalLayout.addWidget(self.labelWordsList)
        self.edit_word_list_path = QtGui.QLineEdit(self.widgetWordList)
        self.edit_word_list_path.setObjectName(_fromUtf8("edit_word_list_path"))
        self.horizontalLayout.addWidget(self.edit_word_list_path)
        self.browseWordList = QtGui.QPushButton(self.widgetWordList)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseWordList.sizePolicy().hasHeightForWidth())
        self.browseWordList.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.browseWordList.setFont(font)
        self.browseWordList.setObjectName(_fromUtf8("browseWordList"))
        self.horizontalLayout.addWidget(self.browseWordList)
        self.verticalLayout.addWidget(self.widgetWordList)
        self.line_9 = QtGui.QFrame(self.groupPreprocessing)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.verticalLayout.addWidget(self.line_9)
        self.widgetStdGrammar = QtGui.QWidget(self.groupPreprocessing)
        self.widgetStdGrammar.setEnabled(False)
        self.widgetStdGrammar.setObjectName(_fromUtf8("widgetStdGrammar"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widgetStdGrammar)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.labelStdGrammar = QtGui.QLabel(self.widgetStdGrammar)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.labelStdGrammar.setFont(font)
        self.labelStdGrammar.setObjectName(_fromUtf8("labelStdGrammar"))
        self.horizontalLayout_2.addWidget(self.labelStdGrammar)
        self.edit_std_grammar_path = QtGui.QLineEdit(self.widgetStdGrammar)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_std_grammar_path.sizePolicy().hasHeightForWidth())
        self.edit_std_grammar_path.setSizePolicy(sizePolicy)
        self.edit_std_grammar_path.setObjectName(_fromUtf8("edit_std_grammar_path"))
        self.horizontalLayout_2.addWidget(self.edit_std_grammar_path)
        self.browseGrammarStd = QtGui.QPushButton(self.widgetStdGrammar)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseGrammarStd.sizePolicy().hasHeightForWidth())
        self.browseGrammarStd.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.browseGrammarStd.setFont(font)
        self.browseGrammarStd.setObjectName(_fromUtf8("browseGrammarStd"))
        self.horizontalLayout_2.addWidget(self.browseGrammarStd)
        self.verticalLayout.addWidget(self.widgetStdGrammar)
        self.widgetScholarSeededOnly = QtGui.QWidget(self.groupPreprocessing)
        self.widgetScholarSeededOnly.setEnabled(False)
        self.widgetScholarSeededOnly.setObjectName(_fromUtf8("widgetScholarSeededOnly"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widgetScholarSeededOnly)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.widgetSSGrammar = QtGui.QWidget(self.widgetScholarSeededOnly)
        self.widgetSSGrammar.setObjectName(_fromUtf8("widgetSSGrammar"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.widgetSSGrammar)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.labelSSGrammar = QtGui.QLabel(self.widgetSSGrammar)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.labelSSGrammar.setFont(font)
        self.labelSSGrammar.setObjectName(_fromUtf8("labelSSGrammar"))
        self.horizontalLayout_12.addWidget(self.labelSSGrammar)
        self.edit_ss_grammar_path = QtGui.QLineEdit(self.widgetSSGrammar)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_ss_grammar_path.sizePolicy().hasHeightForWidth())
        self.edit_ss_grammar_path.setSizePolicy(sizePolicy)
        self.edit_ss_grammar_path.setObjectName(_fromUtf8("edit_ss_grammar_path"))
        self.horizontalLayout_12.addWidget(self.edit_ss_grammar_path)
        self.browseGrammarSS = QtGui.QPushButton(self.widgetSSGrammar)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseGrammarSS.sizePolicy().hasHeightForWidth())
        self.browseGrammarSS.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.browseGrammarSS.setFont(font)
        self.browseGrammarSS.setObjectName(_fromUtf8("browseGrammarSS"))
        self.horizontalLayout_12.addWidget(self.browseGrammarSS)
        self.verticalLayout_4.addWidget(self.widgetSSGrammar)
        self.widgetSSInput = QtGui.QWidget(self.widgetScholarSeededOnly)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetSSInput.sizePolicy().hasHeightForWidth())
        self.widgetSSInput.setSizePolicy(sizePolicy)
        self.widgetSSInput.setObjectName(_fromUtf8("widgetSSInput"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widgetSSInput)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.labelScholarSeededInput = QtGui.QLabel(self.widgetSSInput)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.labelScholarSeededInput.setFont(font)
        self.labelScholarSeededInput.setObjectName(_fromUtf8("labelScholarSeededInput"))
        self.horizontalLayout_3.addWidget(self.labelScholarSeededInput)
        self.edit_scholar_seeded_path = QtGui.QLineEdit(self.widgetSSInput)
        self.edit_scholar_seeded_path.setObjectName(_fromUtf8("edit_scholar_seeded_path"))
        self.horizontalLayout_3.addWidget(self.edit_scholar_seeded_path)
        self.browseScholarKnowledgeFile = QtGui.QPushButton(self.widgetSSInput)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseScholarKnowledgeFile.sizePolicy().hasHeightForWidth())
        self.browseScholarKnowledgeFile.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.browseScholarKnowledgeFile.setFont(font)
        self.browseScholarKnowledgeFile.setObjectName(_fromUtf8("browseScholarKnowledgeFile"))
        self.horizontalLayout_3.addWidget(self.browseScholarKnowledgeFile)
        self.verticalLayout_4.addWidget(self.widgetSSInput)
        self.widgetPrefixNonterminal = QtGui.QWidget(self.widgetScholarSeededOnly)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetPrefixNonterminal.sizePolicy().hasHeightForWidth())
        self.widgetPrefixNonterminal.setSizePolicy(sizePolicy)
        self.widgetPrefixNonterminal.setObjectName(_fromUtf8("widgetPrefixNonterminal"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.widgetPrefixNonterminal)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.labelPrefixNonterminal = QtGui.QLabel(self.widgetPrefixNonterminal)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.labelPrefixNonterminal.setFont(font)
        self.labelPrefixNonterminal.setObjectName(_fromUtf8("labelPrefixNonterminal"))
        self.horizontalLayout_8.addWidget(self.labelPrefixNonterminal)
        self.label_2 = QtGui.QLabel(self.widgetPrefixNonterminal)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_8.addWidget(self.label_2)
        self.edit_prefix_nonterminal = QtGui.QLineEdit(self.widgetPrefixNonterminal)
        self.edit_prefix_nonterminal.setObjectName(_fromUtf8("edit_prefix_nonterminal"))
        self.horizontalLayout_8.addWidget(self.edit_prefix_nonterminal)
        self.verticalLayout_4.addWidget(self.widgetPrefixNonterminal)
        self.widgetSuffixNonterminal = QtGui.QWidget(self.widgetScholarSeededOnly)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetSuffixNonterminal.sizePolicy().hasHeightForWidth())
        self.widgetSuffixNonterminal.setSizePolicy(sizePolicy)
        self.widgetSuffixNonterminal.setObjectName(_fromUtf8("widgetSuffixNonterminal"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.widgetSuffixNonterminal)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.labelSuffixNonterminal = QtGui.QLabel(self.widgetSuffixNonterminal)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.labelSuffixNonterminal.setFont(font)
        self.labelSuffixNonterminal.setObjectName(_fromUtf8("labelSuffixNonterminal"))
        self.horizontalLayout_10.addWidget(self.labelSuffixNonterminal)
        self.label_3 = QtGui.QLabel(self.widgetSuffixNonterminal)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_10.addWidget(self.label_3)
        self.edit_suffix_nonterminal = QtGui.QLineEdit(self.widgetSuffixNonterminal)
        self.edit_suffix_nonterminal.setObjectName(_fromUtf8("edit_suffix_nonterminal"))
        self.horizontalLayout_10.addWidget(self.edit_suffix_nonterminal)
        self.verticalLayout_4.addWidget(self.widgetSuffixNonterminal)
        self.verticalLayout.addWidget(self.widgetScholarSeededOnly)
        self.widgetCascadedOnly = QtGui.QWidget(self.groupPreprocessing)
        self.widgetCascadedOnly.setEnabled(False)
        self.widgetCascadedOnly.setObjectName(_fromUtf8("widgetCascadedOnly"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.widgetCascadedOnly)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.widgetCascadedGrammar_1 = QtGui.QWidget(self.widgetCascadedOnly)
        self.widgetCascadedGrammar_1.setObjectName(_fromUtf8("widgetCascadedGrammar_1"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.widgetCascadedGrammar_1)
        self.horizontalLayout_18.setMargin(0)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.labelCascadedGrammar_1 = QtGui.QLabel(self.widgetCascadedGrammar_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.labelCascadedGrammar_1.setFont(font)
        self.labelCascadedGrammar_1.setObjectName(_fromUtf8("labelCascadedGrammar_1"))
        self.horizontalLayout_18.addWidget(self.labelCascadedGrammar_1)
        self.edit_cascaded_grammar_path_1 = QtGui.QLineEdit(self.widgetCascadedGrammar_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_cascaded_grammar_path_1.sizePolicy().hasHeightForWidth())
        self.edit_cascaded_grammar_path_1.setSizePolicy(sizePolicy)
        self.edit_cascaded_grammar_path_1.setObjectName(_fromUtf8("edit_cascaded_grammar_path_1"))
        self.horizontalLayout_18.addWidget(self.edit_cascaded_grammar_path_1)
        self.browseGrammarCascaded_1 = QtGui.QPushButton(self.widgetCascadedGrammar_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseGrammarCascaded_1.sizePolicy().hasHeightForWidth())
        self.browseGrammarCascaded_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.browseGrammarCascaded_1.setFont(font)
        self.browseGrammarCascaded_1.setObjectName(_fromUtf8("browseGrammarCascaded_1"))
        self.horizontalLayout_18.addWidget(self.browseGrammarCascaded_1)
        self.verticalLayout_9.addWidget(self.widgetCascadedGrammar_1)
        self.widgetCascadedGrammar_2 = QtGui.QWidget(self.widgetCascadedOnly)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetCascadedGrammar_2.sizePolicy().hasHeightForWidth())
        self.widgetCascadedGrammar_2.setSizePolicy(sizePolicy)
        self.widgetCascadedGrammar_2.setObjectName(_fromUtf8("widgetCascadedGrammar_2"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.widgetCascadedGrammar_2)
        self.horizontalLayout_19.setMargin(0)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.labelCascadedGrammar_2 = QtGui.QLabel(self.widgetCascadedGrammar_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.labelCascadedGrammar_2.setFont(font)
        self.labelCascadedGrammar_2.setObjectName(_fromUtf8("labelCascadedGrammar_2"))
        self.horizontalLayout_19.addWidget(self.labelCascadedGrammar_2)
        self.edit_cascaded_grammar_path_2 = QtGui.QLineEdit(self.widgetCascadedGrammar_2)
        self.edit_cascaded_grammar_path_2.setObjectName(_fromUtf8("edit_cascaded_grammar_path_2"))
        self.horizontalLayout_19.addWidget(self.edit_cascaded_grammar_path_2)
        self.browseGrammarCascaded_2 = QtGui.QPushButton(self.widgetCascadedGrammar_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseGrammarCascaded_2.sizePolicy().hasHeightForWidth())
        self.browseGrammarCascaded_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.browseGrammarCascaded_2.setFont(font)
        self.browseGrammarCascaded_2.setObjectName(_fromUtf8("browseGrammarCascaded_2"))
        self.horizontalLayout_19.addWidget(self.browseGrammarCascaded_2)
        self.verticalLayout_9.addWidget(self.widgetCascadedGrammar_2)
        self.widgetPrefixNonterminal_2 = QtGui.QWidget(self.widgetCascadedOnly)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetPrefixNonterminal_2.sizePolicy().hasHeightForWidth())
        self.widgetPrefixNonterminal_2.setSizePolicy(sizePolicy)
        self.widgetPrefixNonterminal_2.setObjectName(_fromUtf8("widgetPrefixNonterminal_2"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.widgetPrefixNonterminal_2)
        self.horizontalLayout_20.setMargin(0)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.labelPrefixNonterminal_2 = QtGui.QLabel(self.widgetPrefixNonterminal_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.labelPrefixNonterminal_2.setFont(font)
        self.labelPrefixNonterminal_2.setObjectName(_fromUtf8("labelPrefixNonterminal_2"))
        self.horizontalLayout_20.addWidget(self.labelPrefixNonterminal_2)
        self.label_6 = QtGui.QLabel(self.widgetPrefixNonterminal_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_20.addWidget(self.label_6)
        self.edit_prefix_nonterminal_2 = QtGui.QLineEdit(self.widgetPrefixNonterminal_2)
        self.edit_prefix_nonterminal_2.setObjectName(_fromUtf8("edit_prefix_nonterminal_2"))
        self.horizontalLayout_20.addWidget(self.edit_prefix_nonterminal_2)
        self.verticalLayout_9.addWidget(self.widgetPrefixNonterminal_2)
        self.widgetSuffixNonterminal_2 = QtGui.QWidget(self.widgetCascadedOnly)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetSuffixNonterminal_2.sizePolicy().hasHeightForWidth())
        self.widgetSuffixNonterminal_2.setSizePolicy(sizePolicy)
        self.widgetSuffixNonterminal_2.setObjectName(_fromUtf8("widgetSuffixNonterminal_2"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.widgetSuffixNonterminal_2)
        self.horizontalLayout_21.setMargin(0)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.labelSuffixNonterminal_2 = QtGui.QLabel(self.widgetSuffixNonterminal_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.labelSuffixNonterminal_2.setFont(font)
        self.labelSuffixNonterminal_2.setObjectName(_fromUtf8("labelSuffixNonterminal_2"))
        self.horizontalLayout_21.addWidget(self.labelSuffixNonterminal_2)
        self.label_7 = QtGui.QLabel(self.widgetSuffixNonterminal_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_21.addWidget(self.label_7)
        self.edit_suffix_nonterminal_2 = QtGui.QLineEdit(self.widgetSuffixNonterminal_2)
        self.edit_suffix_nonterminal_2.setObjectName(_fromUtf8("edit_suffix_nonterminal_2"))
        self.horizontalLayout_21.addWidget(self.edit_suffix_nonterminal_2)
        self.verticalLayout_9.addWidget(self.widgetSuffixNonterminal_2)
        self.verticalLayout.addWidget(self.widgetCascadedOnly)
        self.pushButtonPreprocess = QtGui.QPushButton(self.groupPreprocessing)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.pushButtonPreprocess.setFont(font)
        self.pushButtonPreprocess.setAutoFillBackground(False)
        self.pushButtonPreprocess.setObjectName(_fromUtf8("pushButtonPreprocess"))
        self.verticalLayout.addWidget(self.pushButtonPreprocess)
        self.verticalLayout_5.addWidget(self.groupPreprocessing)
        self.line_5 = QtGui.QFrame(self.frame)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout_5.addWidget(self.line_5)
        self.line_4 = QtGui.QFrame(self.frame)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_5.addWidget(self.line_4)
        self.groupTraining = QtGui.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupTraining.setFont(font)
        self.groupTraining.setObjectName(_fromUtf8("groupTraining"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupTraining)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.widgetRunID = QtGui.QWidget(self.groupTraining)
        self.widgetRunID.setObjectName(_fromUtf8("widgetRunID"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.widgetRunID)
        self.horizontalLayout_17.setMargin(0)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.labelSeparateBy_2 = QtGui.QLabel(self.widgetRunID)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.labelSeparateBy_2.setFont(font)
        self.labelSeparateBy_2.setObjectName(_fromUtf8("labelSeparateBy_2"))
        self.horizontalLayout_17.addWidget(self.labelSeparateBy_2)
        self.label_5 = QtGui.QLabel(self.widgetRunID)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_17.addWidget(self.label_5)
        self.label_4 = QtGui.QLabel(self.widgetRunID)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_17.addWidget(self.label_4)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem)
        self.lineEditRunID = QtGui.QLineEdit(self.widgetRunID)
        self.lineEditRunID.setMaxLength(4)
        self.lineEditRunID.setObjectName(_fromUtf8("lineEditRunID"))
        self.horizontalLayout_17.addWidget(self.lineEditRunID)
        self.verticalLayout_3.addWidget(self.widgetRunID)
        self.widgetSelectPYAG = QtGui.QWidget(self.groupTraining)
        self.widgetSelectPYAG.setObjectName(_fromUtf8("widgetSelectPYAG"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widgetSelectPYAG)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.labelSelectPYAG = QtGui.QLabel(self.widgetSelectPYAG)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.labelSelectPYAG.setFont(font)
        self.labelSelectPYAG.setObjectName(_fromUtf8("labelSelectPYAG"))
        self.horizontalLayout_4.addWidget(self.labelSelectPYAG)
        self.edit_PYAG_binary_path = QtGui.QLineEdit(self.widgetSelectPYAG)
        self.edit_PYAG_binary_path.setObjectName(_fromUtf8("edit_PYAG_binary_path"))
        self.horizontalLayout_4.addWidget(self.edit_PYAG_binary_path)
        self.browsePYAG = QtGui.QPushButton(self.widgetSelectPYAG)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browsePYAG.sizePolicy().hasHeightForWidth())
        self.browsePYAG.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.browsePYAG.setFont(font)
        self.browsePYAG.setObjectName(_fromUtf8("browsePYAG"))
        self.horizontalLayout_4.addWidget(self.browsePYAG)
        self.verticalLayout_3.addWidget(self.widgetSelectPYAG)
        self.widgetPYAGGrammarInput = QtGui.QWidget(self.groupTraining)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetPYAGGrammarInput.sizePolicy().hasHeightForWidth())
        self.widgetPYAGGrammarInput.setSizePolicy(sizePolicy)
        self.widgetPYAGGrammarInput.setObjectName(_fromUtf8("widgetPYAGGrammarInput"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.widgetPYAGGrammarInput)
        self.horizontalLayout_15.setMargin(0)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.labelGrammarInput = QtGui.QLabel(self.widgetPYAGGrammarInput)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.labelGrammarInput.setFont(font)
        self.labelGrammarInput.setObjectName(_fromUtf8("labelGrammarInput"))
        self.horizontalLayout_15.addWidget(self.labelGrammarInput)
        self.edit_pyag_input_grammar_path = QtGui.QLineEdit(self.widgetPYAGGrammarInput)
        self.edit_pyag_input_grammar_path.setObjectName(_fromUtf8("edit_pyag_input_grammar_path"))
        self.horizontalLayout_15.addWidget(self.edit_pyag_input_grammar_path)
        self.browsePYAGGrammar = QtGui.QPushButton(self.widgetPYAGGrammarInput)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browsePYAGGrammar.sizePolicy().hasHeightForWidth())
        self.browsePYAGGrammar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.browsePYAGGrammar.setFont(font)
        self.browsePYAGGrammar.setObjectName(_fromUtf8("browsePYAGGrammar"))
        self.horizontalLayout_15.addWidget(self.browsePYAGGrammar)
        self.verticalLayout_3.addWidget(self.widgetPYAGGrammarInput)
        self.widgetCascadedSettings = QtGui.QWidget(self.groupTraining)
        self.widgetCascadedSettings.setEnabled(False)
        self.widgetCascadedSettings.setObjectName(_fromUtf8("widgetCascadedSettings"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.widgetCascadedSettings)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.widgetPYAGGrammarInput_2 = QtGui.QWidget(self.widgetCascadedSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetPYAGGrammarInput_2.sizePolicy().hasHeightForWidth())
        self.widgetPYAGGrammarInput_2.setSizePolicy(sizePolicy)
        self.widgetPYAGGrammarInput_2.setObjectName(_fromUtf8("widgetPYAGGrammarInput_2"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout(self.widgetPYAGGrammarInput_2)
        self.horizontalLayout_23.setMargin(0)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.labelGrammarInput_2 = QtGui.QLabel(self.widgetPYAGGrammarInput_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.labelGrammarInput_2.setFont(font)
        self.labelGrammarInput_2.setObjectName(_fromUtf8("labelGrammarInput_2"))
        self.horizontalLayout_23.addWidget(self.labelGrammarInput_2)
        self.edit_pyag_input_grammar_path_2 = QtGui.QLineEdit(self.widgetPYAGGrammarInput_2)
        self.edit_pyag_input_grammar_path_2.setReadOnly(True)
        self.edit_pyag_input_grammar_path_2.setObjectName(_fromUtf8("edit_pyag_input_grammar_path_2"))
        self.horizontalLayout_23.addWidget(self.edit_pyag_input_grammar_path_2)
        self.verticalLayout_10.addWidget(self.widgetPYAGGrammarInput_2)
        self.widgetNumberofAffixes = QtGui.QWidget(self.widgetCascadedSettings)
        self.widgetNumberofAffixes.setObjectName(_fromUtf8("widgetNumberofAffixes"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout(self.widgetNumberofAffixes)
        self.horizontalLayout_24.setMargin(0)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.labelNumberofAffixes = QtGui.QLabel(self.widgetNumberofAffixes)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.labelNumberofAffixes.setFont(font)
        self.labelNumberofAffixes.setObjectName(_fromUtf8("labelNumberofAffixes"))
        self.horizontalLayout_24.addWidget(self.labelNumberofAffixes)
        self.label_8 = QtGui.QLabel(self.widgetNumberofAffixes)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_24.addWidget(self.label_8)
        self.spinBoxNumberofAffixes = QtGui.QSpinBox(self.widgetNumberofAffixes)
        self.spinBoxNumberofAffixes.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.spinBoxNumberofAffixes.setMaximum(100)
        self.spinBoxNumberofAffixes.setSingleStep(5)
        self.spinBoxNumberofAffixes.setProperty("value", 10)
        self.spinBoxNumberofAffixes.setObjectName(_fromUtf8("spinBoxNumberofAffixes"))
        self.horizontalLayout_24.addWidget(self.spinBoxNumberofAffixes)
        self.verticalLayout_10.addWidget(self.widgetNumberofAffixes)
        self.widgetCascadedGrammarRegex = QtGui.QWidget(self.widgetCascadedSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetCascadedGrammarRegex.sizePolicy().hasHeightForWidth())
        self.widgetCascadedGrammarRegex.setSizePolicy(sizePolicy)
        self.widgetCascadedGrammarRegex.setObjectName(_fromUtf8("widgetCascadedGrammarRegex"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout(self.widgetCascadedGrammarRegex)
        self.horizontalLayout_22.setMargin(0)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.labelNonterminalRegex = QtGui.QLabel(self.widgetCascadedGrammarRegex)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.labelNonterminalRegex.setFont(font)
        self.labelNonterminalRegex.setObjectName(_fromUtf8("labelNonterminalRegex"))
        self.horizontalLayout_22.addWidget(self.labelNonterminalRegex)
        self.edit_nonterminal_regex = QtGui.QLineEdit(self.widgetCascadedGrammarRegex)
        self.edit_nonterminal_regex.setObjectName(_fromUtf8("edit_nonterminal_regex"))
        self.horizontalLayout_22.addWidget(self.edit_nonterminal_regex)
        self.verticalLayout_10.addWidget(self.widgetCascadedGrammarRegex)
        self.verticalLayout_3.addWidget(self.widgetCascadedSettings)
        self.widgetPYAGWordListInput = QtGui.QWidget(self.groupTraining)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetPYAGWordListInput.sizePolicy().hasHeightForWidth())
        self.widgetPYAGWordListInput.setSizePolicy(sizePolicy)
        self.widgetPYAGWordListInput.setObjectName(_fromUtf8("widgetPYAGWordListInput"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.widgetPYAGWordListInput)
        self.horizontalLayout_16.setMargin(0)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.labelWordListInput = QtGui.QLabel(self.widgetPYAGWordListInput)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.labelWordListInput.setFont(font)
        self.labelWordListInput.setObjectName(_fromUtf8("labelWordListInput"))
        self.horizontalLayout_16.addWidget(self.labelWordListInput)
        self.edit_pyag_input_wordlist = QtGui.QLineEdit(self.widgetPYAGWordListInput)
        self.edit_pyag_input_wordlist.setObjectName(_fromUtf8("edit_pyag_input_wordlist"))
        self.horizontalLayout_16.addWidget(self.edit_pyag_input_wordlist)
        self.browsePYAGWordList = QtGui.QPushButton(self.widgetPYAGWordListInput)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browsePYAGWordList.sizePolicy().hasHeightForWidth())
        self.browsePYAGWordList.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.browsePYAGWordList.setFont(font)
        self.browsePYAGWordList.setObjectName(_fromUtf8("browsePYAGWordList"))
        self.horizontalLayout_16.addWidget(self.browsePYAGWordList)
        self.verticalLayout_3.addWidget(self.widgetPYAGWordListInput)
        self.widgetNumberofIterations = QtGui.QWidget(self.groupTraining)
        self.widgetNumberofIterations.setObjectName(_fromUtf8("widgetNumberofIterations"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widgetNumberofIterations)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.labelNumberofIterations = QtGui.QLabel(self.widgetNumberofIterations)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.labelNumberofIterations.setFont(font)
        self.labelNumberofIterations.setObjectName(_fromUtf8("labelNumberofIterations"))
        self.horizontalLayout_5.addWidget(self.labelNumberofIterations)
        self.spinBoxNumberofIterations = QtGui.QSpinBox(self.widgetNumberofIterations)
        self.spinBoxNumberofIterations.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.spinBoxNumberofIterations.setMaximum(10000)
        self.spinBoxNumberofIterations.setSingleStep(50)
        self.spinBoxNumberofIterations.setObjectName(_fromUtf8("spinBoxNumberofIterations"))
        self.horizontalLayout_5.addWidget(self.spinBoxNumberofIterations)
        self.verticalLayout_3.addWidget(self.widgetNumberofIterations)
        self.pushButtonTrain = QtGui.QPushButton(self.groupTraining)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        self.pushButtonTrain.setFont(font)
        self.pushButtonTrain.setObjectName(_fromUtf8("pushButtonTrain"))
        self.verticalLayout_3.addWidget(self.pushButtonTrain)
        self.verticalLayout_5.addWidget(self.groupTraining)
        self.line = QtGui.QFrame(self.frame)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_5.addWidget(self.line)
        self.line_2 = QtGui.QFrame(self.frame)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_5.addWidget(self.line_2)
        self.groupProcessing = QtGui.QGroupBox(self.frame)
        self.groupProcessing.setObjectName(_fromUtf8("groupProcessing"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupProcessing)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.widgetGrammarFile_2 = QtGui.QWidget(self.groupProcessing)
        self.widgetGrammarFile_2.setObjectName(_fromUtf8("widgetGrammarFile_2"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.widgetGrammarFile_2)
        self.horizontalLayout_11.setMargin(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.labelSelectPYAGOutput = QtGui.QLabel(self.widgetGrammarFile_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.labelSelectPYAGOutput.setFont(font)
        self.labelSelectPYAGOutput.setObjectName(_fromUtf8("labelSelectPYAGOutput"))
        self.horizontalLayout_11.addWidget(self.labelSelectPYAGOutput)
        self.edit_pyags_output_path = QtGui.QLineEdit(self.widgetGrammarFile_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_pyags_output_path.sizePolicy().hasHeightForWidth())
        self.edit_pyags_output_path.setSizePolicy(sizePolicy)
        self.edit_pyags_output_path.setText(_fromUtf8(""))
        self.edit_pyags_output_path.setObjectName(_fromUtf8("edit_pyags_output_path"))
        self.horizontalLayout_11.addWidget(self.edit_pyags_output_path)
        self.browseParseFile = QtGui.QPushButton(self.widgetGrammarFile_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseParseFile.sizePolicy().hasHeightForWidth())
        self.browseParseFile.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.browseParseFile.setFont(font)
        self.browseParseFile.setObjectName(_fromUtf8("browseParseFile"))
        self.horizontalLayout_11.addWidget(self.browseParseFile)
        self.verticalLayout_8.addWidget(self.widgetGrammarFile_2)
        self.widgetNonTerminalsToParse = QtGui.QWidget(self.groupProcessing)
        self.widgetNonTerminalsToParse.setObjectName(_fromUtf8("widgetNonTerminalsToParse"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.widgetNonTerminalsToParse)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.labelNonTerminalsToParse = QtGui.QLabel(self.widgetNonTerminalsToParse)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.labelNonTerminalsToParse.setFont(font)
        self.labelNonTerminalsToParse.setObjectName(_fromUtf8("labelNonTerminalsToParse"))
        self.horizontalLayout_7.addWidget(self.labelNonTerminalsToParse)
        self.lineEditNonTerminalsToParse = QtGui.QLineEdit(self.widgetNonTerminalsToParse)
        self.lineEditNonTerminalsToParse.setObjectName(_fromUtf8("lineEditNonTerminalsToParse"))
        self.horizontalLayout_7.addWidget(self.lineEditNonTerminalsToParse)
        self.verticalLayout_8.addWidget(self.widgetNonTerminalsToParse)
        self.line_3 = QtGui.QFrame(self.groupProcessing)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_8.addWidget(self.line_3)
        self.groupSegmenting = QtGui.QGroupBox(self.groupProcessing)
        self.groupSegmenting.setObjectName(_fromUtf8("groupSegmenting"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupSegmenting)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.widgetFile = QtGui.QWidget(self.groupSegmenting)
        self.widgetFile.setObjectName(_fromUtf8("widgetFile"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widgetFile)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.labelSegmentationFile = QtGui.QLabel(self.widgetFile)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.labelSegmentationFile.setFont(font)
        self.labelSegmentationFile.setObjectName(_fromUtf8("labelSegmentationFile"))
        self.horizontalLayout_6.addWidget(self.labelSegmentationFile)
        self.edit_segmentation_file_path = QtGui.QLineEdit(self.widgetFile)
        self.edit_segmentation_file_path.setObjectName(_fromUtf8("edit_segmentation_file_path"))
        self.horizontalLayout_6.addWidget(self.edit_segmentation_file_path)
        self.browseSegmentationFile = QtGui.QPushButton(self.widgetFile)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseSegmentationFile.sizePolicy().hasHeightForWidth())
        self.browseSegmentationFile.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.browseSegmentationFile.setFont(font)
        self.browseSegmentationFile.setObjectName(_fromUtf8("browseSegmentationFile"))
        self.horizontalLayout_6.addWidget(self.browseSegmentationFile)
        self.verticalLayout_6.addWidget(self.widgetFile)
        self.checkBoxMultiwaySegmentation = QtGui.QCheckBox(self.groupSegmenting)
        self.checkBoxMultiwaySegmentation.setObjectName(_fromUtf8("checkBoxMultiwaySegmentation"))
        self.verticalLayout_6.addWidget(self.checkBoxMultiwaySegmentation)
        self.verticalLayout_8.addWidget(self.groupSegmenting)
        self.pushButtonProcess = QtGui.QPushButton(self.groupProcessing)
        self.pushButtonProcess.setObjectName(_fromUtf8("pushButtonProcess"))
        self.verticalLayout_8.addWidget(self.pushButtonProcess)
        self.verticalLayout_5.addWidget(self.groupProcessing)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.verticalLayout_7.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_25.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionStandard = QtGui.QAction(MainWindow)
        self.actionStandard.setObjectName(_fromUtf8("actionStandard"))
        self.actionScholar_Seeded = QtGui.QAction(MainWindow)
        self.actionScholar_Seeded.setObjectName(_fromUtf8("actionScholar_Seeded"))
        self.actionCascaded = QtGui.QAction(MainWindow)
        self.actionCascaded.setObjectName(_fromUtf8("actionCascaded"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionYashmalik_cse18_itbhu_ac_in = QtGui.QAction(MainWindow)
        self.actionYashmalik_cse18_itbhu_ac_in.setObjectName(_fromUtf8("actionYashmalik_cse18_itbhu_ac_in"))

        self.retranslateUi(MainWindow)
        self.comboBoxSelectSettings.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Roll no. 18075065", None))
        self.labelDirectory.setStatusTip(_translate("MainWindow", "The folder where all the files generated for this run will be saved", None))
        self.labelDirectory.setText(_translate("MainWindow", "Directory", None))
        self.edit_directory_path.setStatusTip(_translate("MainWindow", "Folder path", None))
        self.edit_directory_path.setText(_translate("MainWindow", "./Outputs/TestRun", None))
        self.browseDirectory.setStatusTip(_translate("MainWindow", "Browse", None))
        self.browseDirectory.setText(_translate("MainWindow", "Browse", None))
        self.labelSettings.setStatusTip(_translate("MainWindow", "Select the settings to use", None))
        self.labelSettings.setText(_translate("MainWindow", "Settings", None))
        self.comboBoxSelectSettings.setStatusTip(_translate("MainWindow", "Choose the Settings", None))
        self.comboBoxSelectSettings.setItemText(0, _translate("MainWindow", "Standard", None))
        self.comboBoxSelectSettings.setItemText(1, _translate("MainWindow", "Scholar Seeded", None))
        self.comboBoxSelectSettings.setItemText(2, _translate("MainWindow", "Cascaded", None))
        self.groupPreprocessing.setStatusTip(_translate("MainWindow", "Preprocessing Phase: Prepare the word list and grammar file for input to PYAG", None))
        self.groupPreprocessing.setTitle(_translate("MainWindow", "Preprocessing", None))
        self.labelWordsList.setStatusTip(_translate("MainWindow", "Select Word List File", None))
        self.labelWordsList.setText(_translate("MainWindow", "Words List", None))
        self.edit_word_list_path.setStatusTip(_translate("MainWindow", "List file path", None))
        self.browseWordList.setStatusTip(_translate("MainWindow", "Browse Files", None))
        self.browseWordList.setText(_translate("MainWindow", "Browse", None))
        self.labelStdGrammar.setStatusTip(_translate("MainWindow", "Select Standard Grammar File", None))
        self.labelStdGrammar.setText(_translate("MainWindow", "Std. Grammar", None))
        self.edit_std_grammar_path.setStatusTip(_translate("MainWindow", "Standard Grammar file path", None))
        self.browseGrammarStd.setStatusTip(_translate("MainWindow", "Browse Files", None))
        self.browseGrammarStd.setText(_translate("MainWindow", "Browse", None))
        self.labelSSGrammar.setStatusTip(_translate("MainWindow", "Select ScholarSeeded Grammar File", None))
        self.labelSSGrammar.setText(_translate("MainWindow", "SS Grammar", None))
        self.edit_ss_grammar_path.setStatusTip(_translate("MainWindow", "ScholarSeeded Grammar file path", None))
        self.browseGrammarSS.setStatusTip(_translate("MainWindow", "Browse Files", None))
        self.browseGrammarSS.setText(_translate("MainWindow", "Browse", None))
        self.labelScholarSeededInput.setStatusTip(_translate("MainWindow", "Select Scholar Seeded Knowledge File", None))
        self.labelScholarSeededInput.setText(_translate("MainWindow", "SS Input", None))
        self.edit_scholar_seeded_path.setStatusTip(_translate("MainWindow", "Knowledge file path", None))
        self.browseScholarKnowledgeFile.setStatusTip(_translate("MainWindow", "Browse Files", None))
        self.browseScholarKnowledgeFile.setText(_translate("MainWindow", "Browse", None))
        self.labelPrefixNonterminal.setStatusTip(_translate("MainWindow", "Prefices are seeded into this nonterminal", None))
        self.labelPrefixNonterminal.setText(_translate("MainWindow", "Prefix Nonterminal", None))
        self.label_2.setText(_translate("MainWindow", "(should contain \'Seeded\')", None))
        self.edit_prefix_nonterminal.setStatusTip(_translate("MainWindow", "which nonterminal the prefixes should be seeded into", None))
        self.edit_prefix_nonterminal.setText(_translate("MainWindow", "SeededPrefix", None))
        self.labelSuffixNonterminal.setStatusTip(_translate("MainWindow", "Suffices are seeded into this nonterminal", None))
        self.labelSuffixNonterminal.setText(_translate("MainWindow", "Suffix Nonterminal", None))
        self.label_3.setText(_translate("MainWindow", "(should contain \'Seeded\')", None))
        self.edit_suffix_nonterminal.setStatusTip(_translate("MainWindow", "which nonterminal the suffixes should be seeded into", None))
        self.edit_suffix_nonterminal.setText(_translate("MainWindow", "SeededSuffix", None))
        self.labelCascadedGrammar_1.setStatusTip(_translate("MainWindow", "Select Grammar for first run (a Std. Grammar)", None))
        self.labelCascadedGrammar_1.setText(_translate("MainWindow", "Cascaded Grammar 1", None))
        self.edit_cascaded_grammar_path_1.setStatusTip(_translate("MainWindow", "Grammar 1 file path", None))
        self.edit_cascaded_grammar_path_1.setText(_translate("MainWindow", "./Data/grammars/Std./PrStSu2b_Co_SM.txt", None))
        self.browseGrammarCascaded_1.setStatusTip(_translate("MainWindow", "Browse Files", None))
        self.browseGrammarCascaded_1.setText(_translate("MainWindow", "Browse", None))
        self.labelCascadedGrammar_2.setStatusTip(_translate("MainWindow", "Select Grammar for second run (a SS Grammar)", None))
        self.labelCascadedGrammar_2.setText(_translate("MainWindow", "Cascaded Grammar 2", None))
        self.edit_cascaded_grammar_path_2.setStatusTip(_translate("MainWindow", "Grammar 2 file path", None))
        self.edit_cascaded_grammar_path_2.setText(_translate("MainWindow", "./Data/grammars/SS/PrStSu_SM.txt", None))
        self.browseGrammarCascaded_2.setStatusTip(_translate("MainWindow", "Browse Files", None))
        self.browseGrammarCascaded_2.setText(_translate("MainWindow", "Browse", None))
        self.labelPrefixNonterminal_2.setStatusTip(_translate("MainWindow", "Prefices are seeded into this nonterminal (Grammar 2)", None))
        self.labelPrefixNonterminal_2.setText(_translate("MainWindow", "Prefix Nonterminal", None))
        self.label_6.setText(_translate("MainWindow", "(should contain \'Seeded\')", None))
        self.edit_prefix_nonterminal_2.setStatusTip(_translate("MainWindow", "which nonterminal the prefixes should be seeded into", None))
        self.edit_prefix_nonterminal_2.setText(_translate("MainWindow", "SeededPrefixMorph", None))
        self.labelSuffixNonterminal_2.setStatusTip(_translate("MainWindow", "Suffices are seeded into this nonterminal (Grammar 2)", None))
        self.labelSuffixNonterminal_2.setText(_translate("MainWindow", "Suffix Nonterminal", None))
        self.label_7.setText(_translate("MainWindow", "(should contain \'Seeded\')", None))
        self.edit_suffix_nonterminal_2.setStatusTip(_translate("MainWindow", "which nonterminal the suffixes should be seeded into", None))
        self.edit_suffix_nonterminal_2.setText(_translate("MainWindow", "SeededSuffixMorph", None))
        self.pushButtonPreprocess.setStatusTip(_translate("MainWindow", "Start Preprocessing", None))
        self.pushButtonPreprocess.setText(_translate("MainWindow", "Preprocess", None))
        self.groupTraining.setStatusTip(_translate("MainWindow", "Training Phase: Segment the word list file and generate the grammar rules", None))
        self.groupTraining.setTitle(_translate("MainWindow", "Training", None))
        self.labelSeparateBy_2.setStatusTip(_translate("MainWindow", "All the files generated for this run will begin with this ID (ID+\'.1\' for cascaded 2nd run)", None))
        self.labelSeparateBy_2.setText(_translate("MainWindow", "Run ID", None))
        self.label_5.setText(_translate("MainWindow", "(any existing file will be replaced)", None))
        self.lineEditRunID.setStatusTip(_translate("MainWindow", "integer in [0, 9999], if 0 is the run ID, file generated will begin with \'0\'", None))
        self.lineEditRunID.setText(_translate("MainWindow", "0", None))
        self.labelSelectPYAG.setStatusTip(_translate("MainWindow", "Select PYAG Binary", None))
        self.labelSelectPYAG.setText(_translate("MainWindow", "Select PYAG", None))
        self.edit_PYAG_binary_path.setStatusTip(_translate("MainWindow", "Adaptor Grammars binary file path", None))
        self.edit_PYAG_binary_path.setText(_translate("MainWindow", "../py-cfg/py-cfg-mp", None))
        self.browsePYAG.setStatusTip(_translate("MainWindow", "Browse", None))
        self.browsePYAG.setText(_translate("MainWindow", "Browse", None))
        self.labelGrammarInput.setStatusTip(_translate("MainWindow", "Select Grammar Input for PYAG sampler", None))
        self.labelGrammarInput.setText(_translate("MainWindow", "PYAG Grammar Input", None))
        self.edit_pyag_input_grammar_path.setStatusTip(_translate("MainWindow", "PYAG Grammar Input file path", None))
        self.browsePYAGGrammar.setStatusTip(_translate("MainWindow", "Browse Files", None))
        self.browsePYAGGrammar.setText(_translate("MainWindow", "Browse", None))
        self.labelGrammarInput_2.setStatusTip(_translate("MainWindow", "(Automatic) Grammar 2 Input for PYAG sampler (only for cascaded grammar)", None))
        self.labelGrammarInput_2.setText(_translate("MainWindow", "PYAG Grammar 2 Input", None))
        self.edit_pyag_input_grammar_path_2.setStatusTip(_translate("MainWindow", "PYAG Grammar 2 Input file path (will be decided automatically)", None))
        self.labelNumberofAffixes.setStatusTip(_translate("MainWindow", "Maximum number of Affixes (Prefixes + Suffixes) to copy from the first run", None))
        self.labelNumberofAffixes.setText(_translate("MainWindow", "Limit for number of Affixes to copy", None))
        self.label_8.setText(_translate("MainWindow", "(which are used as seeds for 2nd run)", None))
        self.spinBoxNumberofAffixes.setStatusTip(_translate("MainWindow", "Enter the upper limit for number of affixes to copy", None))
        self.labelNonterminalRegex.setStatusTip(_translate("MainWindow", "Regular expression that specifies which affixes to copy from the segmentation output", None))
        self.labelNonterminalRegex.setText(_translate("MainWindow", "Nonterminal Regex", None))
        self.edit_nonterminal_regex.setStatusTip(_translate("MainWindow", "Regex in the given format only (A|B)", None))
        self.edit_nonterminal_regex.setText(_translate("MainWindow", "(Prefix|Suffix)", None))
        self.labelWordListInput.setStatusTip(_translate("MainWindow", "Select Grammar Input for PYAG sampler", None))
        self.labelWordListInput.setText(_translate("MainWindow", "PYAG Word List Input", None))
        self.edit_pyag_input_wordlist.setStatusTip(_translate("MainWindow", "PYAG Grammar Input file path", None))
        self.browsePYAGWordList.setStatusTip(_translate("MainWindow", "Browse Files", None))
        self.browsePYAGWordList.setText(_translate("MainWindow", "Browse", None))
        self.labelNumberofIterations.setStatusTip(_translate("MainWindow", "Number of Iterations", None))
        self.labelNumberofIterations.setText(_translate("MainWindow", "Number of Iterations", None))
        self.spinBoxNumberofIterations.setStatusTip(_translate("MainWindow", "Enter the number of iterations for sampler", None))
        self.pushButtonTrain.setStatusTip(_translate("MainWindow", "Start Training", None))
        self.pushButtonTrain.setText(_translate("MainWindow", "Train", None))
        self.groupProcessing.setStatusTip(_translate("MainWindow", "Final Processing Phase", None))
        self.groupProcessing.setTitle(_translate("MainWindow", "Processing", None))
        self.labelSelectPYAGOutput.setStatusTip(_translate("MainWindow", "Select the PYAG ouput file to parse (.prs file, which stores morph trees)", None))
        self.labelSelectPYAGOutput.setText(_translate("MainWindow", "Select PYAG Output", None))
        self.edit_pyags_output_path.setStatusTip(_translate("MainWindow", "Parse file path", None))
        self.browseParseFile.setStatusTip(_translate("MainWindow", "Browse Files", None))
        self.browseParseFile.setText(_translate("MainWindow", "Browse", None))
        self.labelNonTerminalsToParse.setStatusTip(_translate("MainWindow", "Non Terminals to Parse in proper Format and Order", None))
        self.labelNonTerminalsToParse.setText(_translate("MainWindow", "Nonterminals To Parse", None))
        self.lineEditNonTerminalsToParse.setStatusTip(_translate("MainWindow", "Non terminals to parse in the given format \"(A|B|C|D)\" and in proper order", None))
        self.lineEditNonTerminalsToParse.setText(_translate("MainWindow", "(Prefix|Stem|Suffix)", None))
        self.groupSegmenting.setStatusTip(_translate("MainWindow", "Segmenting the Words", None))
        self.groupSegmenting.setTitle(_translate("MainWindow", "Segmenting a Text File of words", None))
        self.labelSegmentationFile.setStatusTip(_translate("MainWindow", "Select the file to segment words from", None))
        self.labelSegmentationFile.setText(_translate("MainWindow", "File", None))
        self.edit_segmentation_file_path.setStatusTip(_translate("MainWindow", "Segmentation file path", None))
        self.browseSegmentationFile.setStatusTip(_translate("MainWindow", "Browse Files", None))
        self.browseSegmentationFile.setText(_translate("MainWindow", "Browse", None))
        self.checkBoxMultiwaySegmentation.setStatusTip(_translate("MainWindow", "For example: irre+(place)+ables --> ir+re+(place)+able+s", None))
        self.checkBoxMultiwaySegmentation.setText(_translate("MainWindow", "further split affixes into sub-affixes if applicable", None))
        self.pushButtonProcess.setStatusTip(_translate("MainWindow", "Process the parse file into human readable format and segment word file", None))
        self.pushButtonProcess.setText(_translate("MainWindow", "Process", None))
        self.actionStandard.setText(_translate("MainWindow", "Standard", None))
        self.actionScholar_Seeded.setText(_translate("MainWindow", "Scholar Seeded", None))
        self.actionCascaded.setText(_translate("MainWindow", "Cascaded", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionYashmalik_cse18_itbhu_ac_in.setText(_translate("MainWindow", "yashmalik.cse18@itbhu.ac.in", None))

